port=53
no-hosts
addn-hosts=/etc/hosts-dnsmasq
expand-hosts
domain-needed
bogus-priv

address=/#/192.168.10.1

interface=<interface>
dhcp-range=192.168.10.2,192.168.10.255,255.255.255.0,12h
dhcp-option=option:router,192.168.10.1